services:
  gorave-redis:
    image: redis:alpine
    container_name: gorave-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  gorave-server:
    build:
      context: ./server
    container_name: gorave-server
    env_file:
      - ./server/.env
    expose:
      - "8000"
    depends_on:
      - gorave-redis
    restart: unless-stopped
