-- ============================================================
-- ContentOS — Database Schema (auto-generated by scripts/dump_schema.py)
-- DO NOT EDIT BY HAND — re-run the script to regenerate.
-- ============================================================

-- ── Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.alembic_version (
  version_num character varying(32) NOT NULL,
  CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.follows (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  follower_id uuid NOT NULL,
  following_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT follows_check CHECK (follower_id <> following_id),
  CONSTRAINT follows_pkey PRIMARY KEY (id),
  CONSTRAINT follows_follower_id_following_id_key UNIQUE (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  token_hash character varying(255) NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.user_photos (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL,
  url text NOT NULL,
  r2_path text NOT NULL,
  position smallint DEFAULT 0 NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_photos_pkey PRIMARY KEY (id),
  CONSTRAINT uq_user_photos_position UNIQUE (user_id, "position")
);

CREATE TABLE IF NOT EXISTS public.users (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  phone character varying(15) NOT NULL,
  country_code character varying(5) DEFAULT '+91'::character varying NOT NULL,
  name character varying(100),
  dob date,
  gender character varying(30),
  city character varying(100),
  lat numeric(9,6),
  lng numeric(9,6),
  voice_url text,
  voice_r2_path text,
  interests text[] DEFAULT '{}'::text[],
  profile_complete boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bio text,
  badges text[] DEFAULT ARRAY['🔥 Vybe Starter'::text, '✨ Early Adopter'::text, '🎙️ Voice Ready'::text, '🌟 Main Character'::text],
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_phone_key UNIQUE (phone)
);

-- ── Foreign Keys ────────────────────────────────────────────────────────────
ALTER TABLE public.follows ADD CONSTRAINT follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.follows ADD CONSTRAINT follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.refresh_tokens ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_photos ADD CONSTRAINT user_photos_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX idx_follows_follower ON public.follows USING btree (follower_id);
CREATE INDEX idx_follows_following ON public.follows USING btree (following_id);
CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id);
CREATE INDEX idx_users_phone ON public.users USING btree (phone);

-- ── Triggers ────────────────────────────────────────────────────────────────
-- TRIGGER users_updated_at BEFORE UPDATE ON public.users: EXECUTE FUNCTION update_updated_at()
