import os
import sys
import textwrap
from pathlib import Path

import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

# ── resolve paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
SERVER_DIR = SCRIPT_DIR.parent
QUERIES_SQL = SERVER_DIR / "queries.sql"

load_dotenv(SERVER_DIR / ".env")

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    sys.exit("ERROR: DATABASE_URL is not set in .env or environment.")


def fetch(cur, sql, params=None):
    cur.execute(sql, params or ())
    return cur.fetchall()


def dump_schema(cur) -> str:
    lines: list[str] = []

    lines.append(
        "-- ============================================================\n"
        "-- ContentOS — Database Schema (auto-generated by scripts/dump_schema.py)\n"
        "-- DO NOT EDIT BY HAND — re-run the script to regenerate.\n"
        "-- ============================================================\n"
    )

    # ── enums ─────────────────────────────────────────────────────────────────
    enums = fetch(
        cur,
        """
        SELECT t.typname AS name,
               array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
        FROM   pg_type t
        JOIN   pg_enum e ON e.enumtypid = t.oid
        JOIN   pg_namespace n ON n.oid = t.typnamespace
        WHERE  n.nspname = 'public'
        GROUP  BY t.typname
        ORDER  BY t.typname
        """,
    )
    if enums:
        lines.append("\n-- ── Enums ───────────────────────────────────────────────────────────────────\n")
        for e in enums:
            vals = ", ".join(f"'{v}'" for v in e["labels"])
            lines.append(f"CREATE TYPE public.{e['name']} AS ENUM ({vals});\n")

    # ── sequences ─────────────────────────────────────────────────────────────
    # Dump sequences before tables so columns with `DEFAULT nextval(...)` resolve.
    sequences = fetch(
        cur,
        """
        SELECT sequence_name
        FROM   information_schema.sequences
        WHERE  sequence_schema = 'public'
        ORDER  BY sequence_name
        """,
    )
    if sequences:
        lines.append("\n-- ── Sequences ───────────────────────────────────────────────────────────────\n")
        for s in sequences:
            lines.append(f"CREATE SEQUENCE IF NOT EXISTS public.{s['sequence_name']};\n")

    # ── tables ────────────────────────────────────────────────────────────────
    tables = fetch(
        cur,
        """
        SELECT tablename
        FROM   pg_tables
        WHERE  schemaname = 'public'
        ORDER  BY tablename
        """,
    )

    lines.append("\n-- ── Tables ──────────────────────────────────────────────────────────────────\n")

    # Collect FK statements to emit after all CREATE TABLEs (avoids ordering issues).
    fk_statements: list[str] = []

    for trow in tables:
        tname = trow["tablename"]
        lines.append(f"\nCREATE TABLE IF NOT EXISTS public.{tname} (\n")

        # columns
        cols = fetch(
            cur,
            """
            SELECT a.attname                                          AS col,
                   pg_catalog.format_type(a.atttypid, a.atttypmod)   AS dtype,
                   a.attnotnull                                       AS notnull,
                   pg_get_expr(d.adbin, d.adrelid)                   AS default_val
            FROM   pg_attribute a
            LEFT   JOIN pg_attrdef d
                   ON  d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE  a.attrelid = %s::regclass
              AND  a.attnum   > 0
              AND  NOT a.attisdropped
            ORDER  BY a.attnum
            """,
            (f"public.{tname}",),
        )

        col_defs = []
        for c in cols:
            parts = [f"  {c['col']} {c['dtype']}"]
            if c["default_val"]:
                parts.append(f"DEFAULT {c['default_val']}")
            if c["notnull"]:
                parts.append("NOT NULL")
            col_defs.append(" ".join(parts))

        # constraints — inline pk/unique/check; defer FKs to ALTER TABLE.
        constraints = fetch(
            cur,
            """
            SELECT conname, contype, pg_get_constraintdef(oid, true) AS def
            FROM   pg_constraint
            WHERE  conrelid = %s::regclass
              AND  contype  IN ('p','u','f','c')
            ORDER  BY contype, conname
            """,
            (f"public.{tname}",),
        )
        for con in constraints:
            if con["contype"] == "f":
                fk_statements.append(
                    f"ALTER TABLE public.{tname} "
                    f"ADD CONSTRAINT {con['conname']} {con['def']};\n"
                )
            else:
                col_defs.append(f"  CONSTRAINT {con['conname']} {con['def']}")

        lines.append(",\n".join(col_defs) + "\n")
        lines.append(");\n")

    # ── foreign keys (emitted after all tables exist) ─────────────────────────
    if fk_statements:
        lines.append("\n-- ── Foreign Keys ────────────────────────────────────────────────────────────\n")
        for stmt in fk_statements:
            lines.append(stmt)

    # ── indexes (non-pk, non-constraint) ──────────────────────────────────────
    indexes = fetch(
        cur,
        """
        SELECT indexname, indexdef
        FROM   pg_indexes
        WHERE  schemaname = 'public'
          AND  indexname NOT IN (
               SELECT conname FROM pg_constraint WHERE contype IN ('p','u')
          )
        ORDER  BY tablename, indexname
        """,
    )
    if indexes:
        lines.append("\n-- ── Indexes ─────────────────────────────────────────────────────────────────\n")
        for idx in indexes:
            lines.append(f"{idx['indexdef']};\n")

    # ── functions / triggers (optional, lightweight) ───────────────────────────
    triggers = fetch(
        cur,
        """
        SELECT trigger_name, event_object_table, action_timing, event_manipulation,
               action_statement
        FROM   information_schema.triggers
        WHERE  trigger_schema = 'public'
        ORDER  BY event_object_table, trigger_name
        """,
    )
    if triggers:
        lines.append("\n-- ── Triggers ────────────────────────────────────────────────────────────────\n")
        for t in triggers:
            lines.append(
                f"-- TRIGGER {t['trigger_name']} "
                f"{t['action_timing']} {t['event_manipulation']} "
                f"ON public.{t['event_object_table']}: {t['action_statement']}\n"
            )

    return "".join(lines)


def main():
    conn = psycopg2.connect(DATABASE_URL)
    conn.autocommit = True
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    print("Connected to database. Introspecting schema…")
    sql = dump_schema(cur)

    cur.close()
    conn.close()

    QUERIES_SQL.write_text(sql, encoding="utf-8")
    print(f"Written: {QUERIES_SQL}")
    print(f"  {sql.count(chr(10))} lines, {len(sql):,} bytes")


if __name__ == "__main__":
    main()
